# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source :gemcutter

gem "distribution", ">=0.4.0"
gem "green_shoes", ">=1.0.282" #:path => "/home/jwoods/green_shoes" #:git => "git://github.com/ashbb/green_shoes.git"
gem "statsample", ">=1.1.0"
gem "gsl", "~>1.14.5"
gem "rsvg2", "~>1.0.0"
gem "rubyvis", ">=0.4.0"

gem "hoe", "~>2.12", :group => [:development, :test]
gem "rdoc", ">=0", :group => [:development, :test]
gem "rspec", ">=2.0", :group => [:development, :test]
gem "haml", ">=0", :group => [:development, :test]
gem "coderay", ">=0", :group => [:development, :test]
gem "nokogiri", ">=0", :group => [:development, :test]
gem "RedCloth", ">=0", :group => [:development, :test]
gem "shoulda", "~>2.11", :group => [:development, :test]
gem "gtksourceview2", ">=0", :group => [:development, :test]
gem "hoe-gemspec", "~>1.0", :group => [:development, :test]
gem "hoe-bundler", "~>1.1", :group => [:development, :test]
gem "minitest", "~>2.0", :group => [:development, :test]
gem "hoe", "~>2.12", :group => [:development, :test]

# vim: syntax=ruby
